//cant get this to fail to test function application tests


void main(){
	fun("arg",foo(bar()),6*2);


}